export type OperationLogDto = {
  id: string;
  operationType: string;
  notes?: string | null;
  beforePath?: string | null;
  afterPath?: string | null;
  createdAt: string;
};

export type MaterialCategoryDto = {
  id: string;
  name: string;
  relativePath?: string | null;
  assetType: string;
  status: string;
  allowUpload: boolean;
};

export type DerivativeFileDto = {
  type: "THUMBNAIL" | "PREVIEW_MP4" | "PROXY_MP4" | "AI_FRAME" | "AUDIO" | "SUBTITLE" | "METADATA_JSON" | "OTHER";
  status: "QUEUED" | "PROCESSING" | "READY" | "FAILED" | "DELETED";
  relativePath: string;
  fileSize?: number | null;
  width?: number | null;
  height?: number | null;
  duration?: number | null;
  frameIndex?: number | null;
  errorMessage?: string | null;
  updatedAt: string;
};

export type AIAnalysisJobDto = {
  id: string;
  providerType: string;
  providerName?: string | null;
  modelName?: string | null;
  status: string;
  usedFallback: boolean;
  fallbackProviderType?: string | null;
  confidence?: number | null;
  durationMs?: number | null;
  errorCode?: string | null;
  errorMessage?: string | null;
  createdAt: string;
  completedAt?: string | null;
};

export type MaterialDto = {
  id: string;
  materialId: string;
  assetType: "ACCOUNT_MATERIAL" | "PRODUCT_MATERIAL" | "REFERENCE_VIDEO" | "PUBLIC_RESOURCE" | "UNKNOWN";
  ingestSource?: string;
  originalFileName: string;
  storedFileName: string;
  originalPath?: string | null;
  relativePath: string;
  absolutePath?: string;
  thumbnailPath?: string | null;
  fileSize: number;
  mimeType?: string | null;
  duration?: number | null;
  width?: number | null;
  height?: number | null;
  orientation?: string | null;
  shooterId?: string | null;
  shooterName?: string | null;
  uploaderName?: string | null;
  categoryId?: string | null;
  userSelectedCategoryId?: string | null;
  aiSuggestedCategoryId?: string | null;
  finalCategoryId?: string | null;
  categoryPath?: string | null;
  categoryName?: string | null;
  category?: MaterialCategoryDto | null;
  userSelectedCategory?: MaterialCategoryDto | null;
  aiSuggestedCategory?: MaterialCategoryDto | null;
  finalCategory?: MaterialCategoryDto | null;
  userSelectedRootCategory?: string | null;
  userSelectedSubCategory?: string | null;
  finalRootCategory?: string | null;
  finalSubCategory?: string | null;
  aiSuggestedRootCategory?: string | null;
  aiSuggestedSubCategory?: string | null;
  classificationConflict?: boolean;
  customTags?: unknown;
  aiEmotionTags?: unknown;
  aiUsageTags?: unknown;
  aiSceneTags?: unknown;
  aiSubjectTags?: unknown;
  aiActionTags?: unknown;
  conflictReason?: string | null;
  subjectType?: string | null;
  visualTags?: unknown;
  contentIntent?: string | null;
  contentLongevity?: string | null;
  topicName?: string | null;
  topicSuggestion?: string | null;
  searchText?: string | null;
  primaryCategory: string;
  subject?: string | null;
  scene?: string | null;
  action?: string | null;
  usage?: string | null;
  aiSummary?: string | null;
  aiConfidence?: number | null;
  aiResult?: unknown;
  humanTags?: unknown;
  humanConfirmed: boolean;
  needsHumanReview: boolean;
  status: string;
  notes?: string | null;
  usageCount?: number;
  packageUsageCount?: number;
  finishedWorkUsageCount?: number;
  usageState?: "unused" | "packaged_only" | "used_in_finished_work" | "reused" | "all";
  createdAt: string;
  updatedAt?: string;
  operationLogs?: OperationLogDto[];
  derivativeFiles?: DerivativeFileDto[];
  aiAnalysisJobs?: AIAnalysisJobDto[];
};
