import type React from "react";

import { DEFAULT_THEME } from "@/lib/app-config/default-theme";

const theme = DEFAULT_THEME;
const contentMaxWidthClass = "max-w-[var(--skin-content-max-width)]";
const typography = {
  pageTitle: "text-[length:var(--skin-text-page-title)] leading-[var(--skin-leading-page-title)] font-semibold tracking-normal text-foreground sm:text-[length:var(--skin-text-page-title-desktop)]",
  pageDescription: "text-[length:var(--skin-text-page-description)] leading-[var(--skin-leading-page-description)] text-muted-foreground",
  sectionTitle: "text-[length:var(--skin-text-section-title)] leading-[var(--skin-leading-section-title)] font-semibold text-foreground",
  panelTitle: "text-[length:var(--skin-text-panel-title)] leading-[var(--skin-leading-panel-title)] font-semibold text-foreground",
  cardTitle: "text-[length:var(--skin-text-card-title)] leading-[var(--skin-leading-card-title)] font-semibold text-foreground",
  body: "text-[length:var(--skin-text-body)] leading-[var(--skin-leading-body)]",
  bodyDense: "text-[length:var(--skin-text-body-dense)] leading-[var(--skin-leading-body-dense)]",
  label: "text-[length:var(--skin-text-label)] leading-[var(--skin-leading-label)] text-muted-foreground",
  value: "text-[length:var(--skin-text-value)] leading-[var(--skin-leading-value)] text-foreground",
  meta: "text-[length:var(--skin-text-meta)] leading-[var(--skin-leading-meta)] text-muted-foreground",
  path: "break-all text-[length:var(--skin-text-path)] leading-[var(--skin-leading-path)] text-muted-foreground",
  technical: "text-[length:var(--skin-text-technical)] leading-[var(--skin-leading-technical)] text-muted-foreground",
  tableHead: "text-[length:var(--skin-text-table-head)] leading-[var(--skin-leading-table-head)] text-muted-foreground",
  tableCell: "text-[length:var(--skin-text-table-cell)] leading-[var(--skin-leading-table-cell)]",
  badge: "text-[length:var(--skin-text-badge)] leading-[var(--skin-leading-badge)]",
  button: "text-[length:var(--skin-text-button)] leading-[var(--skin-leading-button)]",
  input: "text-[length:var(--skin-text-input)] leading-[var(--skin-leading-input)]"
} as const;
const statusClass = (tone: keyof typeof theme.status) => ({
  tone,
  pill: [
    "inline-flex items-center gap-1 rounded-[var(--skin-radius-full)] border px-2 py-0.5 font-medium",
    typography.badge,
    theme.status[tone].background,
    theme.status[tone].border,
    theme.status[tone].text
  ].join(" "),
  badge: [
    "inline-flex items-center gap-1 rounded-[var(--skin-radius-control)] px-2 py-1 font-medium",
    typography.badge,
    theme.status[tone].background,
    theme.status[tone].text
  ].join(" "),
  dot: `h-1.5 w-1.5 rounded-full ${theme.status[tone].dot}`,
  icon: theme.status[tone].icon,
  text: theme.status[tone].text,
  background: theme.status[tone].background,
  border: theme.status[tone].border
});

export const skin = {
  theme,
  vars: {
    "--background": theme.colors.background,
    "--foreground": theme.colors.foreground,
    "--muted": theme.colors.muted,
    "--muted-foreground": theme.colors.mutedForeground,
    "--card": theme.colors.card,
    "--card-foreground": theme.colors.cardForeground,
    "--border": theme.colors.border,
    "--primary": theme.colors.primary,
    "--primary-foreground": theme.colors.primaryForeground,
    "--accent": theme.colors.accent,
    "--accent-foreground": theme.colors.accentForeground,
    "--destructive": theme.colors.destructive,
    "--destructive-foreground": theme.colors.destructiveForeground,
    "--ring": theme.colors.ring,
    "--skin-page-bg": theme.surface.page,
    "--skin-surface-page": theme.surface.page,
    "--skin-panel-bg": theme.surface.panel,
    "--skin-surface-panel": theme.surface.panel,
    "--skin-header-bg": theme.surface.header,
    "--skin-muted-bg": theme.surface.muted,
    "--skin-surface-muted": theme.surface.muted,
    "--skin-surface-subtle": theme.surface.subtle,
    "--skin-surface-raised": theme.surface.raised,
    "--skin-surface-table-header": theme.surface.tableHeader,
    "--skin-surface-hover": theme.surface.hover,
    "--skin-surface-selected": theme.surface.selected,
    "--skin-surface-input": theme.surface.input,
    "--skin-overlay": theme.surface.overlay,
    "--skin-border": theme.border.default,
    "--skin-border-subtle": theme.border.subtle,
    "--skin-border-strong": theme.border.strong,
    "--skin-border-focus": theme.border.focus,
    "--skin-sidebar-border": theme.border.sidebar,
    "--skin-sidebar-bg": theme.surface.sidebar,
    "--skin-sidebar-muted": theme.surface.sidebarMuted,
    "--skin-sidebar-panel": theme.surface.sidebarPanel,
    "--skin-sidebar-active": theme.surface.sidebarActive,
    "--skin-sidebar-collapsed-width": theme.layout.sidebarCollapsedWidth,
    "--skin-sidebar-expanded-width": theme.layout.sidebarExpandedWidth,
    "--skin-header-height": theme.layout.headerHeight,
    "--skin-header-height-mobile": theme.layout.headerHeightMobile,
    "--skin-content-max-width": theme.layout.contentMaxWidth,
    "--skin-content-inset-desktop": theme.layout.contentInsetDesktop,
    "--skin-dashboard-aside-width": theme.layout.dashboardAsideWidth,
    "--skin-drawer-width": theme.layout.drawerWidth,
    "--skin-upload-aside-width": theme.layout.widths.uploadAside,
    "--skin-upload-content-max-width": theme.layout.widths.uploadContentMax,
    "--skin-library-sidebar-width": theme.layout.widths.librarySidebar,
    "--skin-library-sidebar-collapsed-width": theme.layout.widths.librarySidebarCollapsed,
    "--skin-library-content-max-width": theme.layout.widths.libraryContentMax,
    "--skin-library-grid-sm-min": theme.layout.widths.libraryGridSmallMin,
    "--skin-library-grid-md-min": theme.layout.widths.libraryGridMediumMin,
    "--skin-library-grid-lg-min": theme.layout.widths.libraryGridLargeMin,
    "--skin-mobile-drawer-width": theme.layout.widths.mobileDrawer,
    "--skin-mobile-drawer-max-width": theme.layout.widths.mobileDrawerMax,
    "--skin-modal-width-sm": theme.layout.widths.modalSm,
    "--skin-modal-width-md": theme.layout.widths.modalMd,
    "--skin-modal-width-lg": theme.layout.widths.modalLg,
    "--skin-toolbar-min-height": theme.layout.heights.toolbarMin,
    "--skin-mobile-bottom-bar-height": theme.layout.heights.mobileBottomBar,
    "--skin-media-placeholder-height-sm": theme.layout.heights.mediaPlaceholderSm,
    "--skin-media-placeholder-height-md": theme.layout.heights.mediaPlaceholderMd,
    "--skin-media-placeholder-height-lg": theme.layout.heights.mediaPlaceholderLg,
    "--skin-thumbnail-height-sm": theme.layout.heights.thumbnailSmall,
    "--skin-thumbnail-height-md": theme.layout.heights.thumbnailMedium,
    "--skin-thumbnail-height-lg": theme.layout.heights.thumbnailLarge,
    "--skin-empty-state-min-height": theme.layout.heights.emptyStateMin,
    "--skin-upload-dropzone-min-height": theme.layout.heights.uploadDropzoneMin,
    "--skin-category-root-tab-min-height": theme.layout.heights.categoryRootTabMin,
    "--skin-category-mobile-row-min-height": theme.layout.heights.categoryMobileRowMin,
    "--skin-radius-xs": theme.radius.xs,
    "--skin-radius-sm": theme.radius.sm,
    "--skin-radius-control": theme.radius.control,
    "--skin-radius-panel": theme.radius.panel,
    "--skin-radius-card": theme.radius.card,
    "--skin-radius-section": theme.radius.section,
    "--skin-radius-full": theme.radius.full,
    "--skin-shadow-panel": theme.shadow.panel,
    "--skin-shadow-card": theme.shadow.card,
    "--skin-shadow-elevated": theme.shadow.elevated,
    "--skin-shadow-focus": theme.shadow.focus,
    "--skin-shadow-sticky-action": "0 -8px 24px rgba(15, 23, 42, 0.06)",
    "--skin-media-thumbnail-bg": theme.media.thumbnailBackground,
    "--skin-media-placeholder-bg": theme.media.placeholderBackground,
    "--skin-media-placeholder-border": theme.media.placeholderBorder,
    "--skin-media-placeholder-icon": theme.media.placeholderIcon,
    "--skin-media-preview-bg": theme.media.previewBackground,
    "--skin-touch-target-min-height": theme.button.touchTargetMinHeight,
    "--skin-icon-button-sm": theme.button.iconOnlySm,
    "--skin-icon-button-md": theme.button.iconOnlyMd,
    "--skin-toolbar-control-height": theme.button.toolbarControlHeight,
    "--skin-control-height-sm": theme.density.controlHeight.sm,
    "--skin-control-height-md": theme.density.controlHeight.md,
    "--skin-control-height-lg": theme.density.controlHeight.lg,
    "--skin-card-padding": theme.density.cardPadding.base,
    "--skin-card-padding-compact": theme.density.cardPadding.compact,
    "--skin-card-padding-spacious": theme.density.cardPadding.spacious,
    "--skin-panel-padding": theme.density.panelPadding.base,
    "--skin-panel-padding-compact": theme.density.panelPadding.compact,
    "--skin-panel-padding-spacious": theme.density.panelPadding.spacious,
    "--skin-content-gap": theme.density.contentGap.md,
    "--skin-section-gap": theme.density.sectionGap.md,
    "--skin-text-page-title": theme.typography.pageTitle.base,
    "--skin-text-page-title-desktop": theme.typography.pageTitle.desktop,
    "--skin-leading-page-title": theme.typography.pageTitle.lineHeight,
    "--skin-text-page-description": theme.typography.pageDescription.size,
    "--skin-leading-page-description": theme.typography.pageDescription.lineHeight,
    "--skin-text-section-title": theme.typography.sectionTitle.size,
    "--skin-leading-section-title": theme.typography.sectionTitle.lineHeight,
    "--skin-text-panel-title": theme.typography.panelTitle.size,
    "--skin-leading-panel-title": theme.typography.panelTitle.lineHeight,
    "--skin-text-card-title": theme.typography.cardTitle.size,
    "--skin-leading-card-title": theme.typography.cardTitle.lineHeight,
    "--skin-text-body": theme.typography.body.size,
    "--skin-leading-body": theme.typography.body.lineHeight,
    "--skin-text-body-dense": theme.typography.bodyDense.size,
    "--skin-leading-body-dense": theme.typography.bodyDense.lineHeight,
    "--skin-text-label": theme.typography.label.size,
    "--skin-leading-label": theme.typography.label.lineHeight,
    "--skin-text-value": theme.typography.value.size,
    "--skin-leading-value": theme.typography.value.lineHeight,
    "--skin-text-meta": theme.typography.meta.size,
    "--skin-leading-meta": theme.typography.meta.lineHeight,
    "--skin-text-path": theme.typography.path.size,
    "--skin-leading-path": theme.typography.path.lineHeight,
    "--skin-text-technical": theme.typography.technical.size,
    "--skin-leading-technical": theme.typography.technical.lineHeight,
    "--skin-text-table-head": theme.typography.tableHead.size,
    "--skin-leading-table-head": theme.typography.tableHead.lineHeight,
    "--skin-text-table-cell": theme.typography.tableCell.size,
    "--skin-leading-table-cell": theme.typography.tableCell.lineHeight,
    "--skin-text-badge": theme.typography.badge.size,
    "--skin-leading-badge": theme.typography.badge.lineHeight,
    "--skin-text-button": theme.typography.button.size,
    "--skin-leading-button": theme.typography.button.lineHeight,
    "--skin-text-input": theme.typography.input.size,
    "--skin-leading-input": theme.typography.input.lineHeight
  } as React.CSSProperties,
  typography,
  page: "min-h-screen overflow-x-hidden bg-[color:var(--skin-page-bg)] text-foreground",
  shell: {
    drawerContentOffset: "lg:pl-[var(--skin-sidebar-collapsed-width)]",
    standardContentOffset: "lg:pl-[var(--skin-sidebar-expanded-width)]",
    header: "sticky top-0 z-20 border-b border-[color:var(--skin-border)] bg-[color:var(--skin-header-bg)]/95 backdrop-blur supports-[backdrop-filter]:bg-[color:var(--skin-header-bg)]/90",
    headerInner: `ml-0 mr-auto flex min-h-[var(--skin-header-height-mobile)] w-full ${contentMaxWidthClass} flex-wrap items-center gap-2 px-3 py-2 sm:px-4 lg:h-[var(--skin-header-height)] lg:flex-nowrap lg:px-[var(--skin-content-inset-desktop)] lg:py-0`,
    main: `ml-0 mr-auto w-full ${contentMaxWidthClass} min-w-0 p-3 sm:p-4 lg:p-[var(--skin-content-inset-desktop)]`,
    search: `min-w-0 flex-1 items-center gap-2 rounded-[var(--skin-radius-full)] border border-[color:var(--skin-border)] bg-[color:var(--skin-surface-input)] py-1.5 pl-3 pr-1.5 text-muted-foreground shadow-[var(--skin-shadow-card)] lg:flex lg:max-w-2xl ${typography.input}`
  },
  sidebar: {
    base: "fixed inset-y-0 left-0 z-40 flex w-[var(--skin-sidebar-expanded-width)] flex-col border-r border-[color:var(--skin-sidebar-border)] bg-[color:var(--skin-sidebar-bg)] text-white transition-all duration-200 lg:translate-x-0",
    collapsed: "w-[var(--skin-sidebar-collapsed-width)]",
    logo: "flex h-[var(--skin-header-height)] items-center gap-3 border-b border-[color:var(--skin-sidebar-border)] px-4",
    logoMark: "flex h-8 w-8 items-center justify-center rounded-[var(--skin-radius-control)] bg-white/10 text-emerald-100 ring-1 ring-white/10",
    item: "group/navitem relative flex items-center gap-3 rounded-[var(--skin-radius-control)] px-3 py-2.5 text-sm font-medium text-white/80 transition hover:bg-white/10 hover:text-white",
    itemActive: "bg-[color:var(--skin-sidebar-active)] text-white shadow-sm ring-1 ring-white/10",
    tooltip: "pointer-events-none absolute left-[calc(var(--skin-sidebar-collapsed-width)-2px)] z-50 hidden whitespace-nowrap rounded-[var(--skin-radius-sm)] bg-slate-950 px-2 py-1 text-xs text-white opacity-0 shadow-[var(--skin-shadow-elevated)] transition group-hover/navitem:opacity-100 lg:group-hover/navitem:block",
    userPanel: "rounded-[var(--skin-radius-panel)] bg-[color:var(--skin-sidebar-panel)] p-3 ring-1 ring-white/10",
    mutedText: "text-[color:var(--skin-sidebar-muted)]"
  },
  buttonBase: "rounded-[var(--skin-radius-control)]",
  cardBase: "rounded-[var(--skin-radius-card)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] text-card-foreground shadow-[var(--skin-shadow-card)]",
  panel: "rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] shadow-[var(--skin-shadow-panel)]",
  mutedPanel: "rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border-subtle)] bg-[color:var(--skin-muted-bg)]",
  raisedPanel: "rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border)] bg-[color:var(--skin-surface-raised)] shadow-[var(--skin-shadow-card)]",
  toolbar: "rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] p-3 shadow-[var(--skin-shadow-panel)]",
  section: "space-y-3",
  sectionHeader: "flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between",
  card: "overflow-hidden rounded-[var(--skin-radius-card)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] shadow-[var(--skin-shadow-card)] transition hover:border-primary/40 hover:shadow-[var(--skin-shadow-panel)]",
  listItem: "rounded-[var(--skin-radius-control)] border border-[color:var(--skin-border-subtle)] bg-[color:var(--skin-panel-bg)] transition hover:border-[color:var(--skin-border-strong)] hover:bg-[color:var(--skin-surface-hover)]",
  formControl:
    `flex h-[var(--skin-control-height-md)] w-full rounded-[var(--skin-radius-control)] border border-[color:var(--skin-border)] bg-[color:var(--skin-surface-input)] px-3 py-2 shadow-[var(--skin-shadow-card)] outline-none transition placeholder:text-muted-foreground focus:border-primary/60 focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 ${typography.input}`,
  textarea:
    `flex min-h-24 w-full rounded-[var(--skin-radius-control)] border border-[color:var(--skin-border)] bg-[color:var(--skin-surface-input)] px-3 py-2 shadow-[var(--skin-shadow-card)] outline-none transition placeholder:text-muted-foreground focus:border-primary/60 focus:ring-2 focus:ring-ring disabled:cursor-not-allowed disabled:opacity-50 ${typography.input}`,
  table: {
    wrapper: "thin-scrollbar overflow-auto rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] shadow-[var(--skin-shadow-panel)]",
    header: `bg-[color:var(--skin-surface-table-header)] ${typography.tableHead}`,
    row: "border-b border-[color:var(--skin-border-subtle)] last:border-b-0 hover:bg-[color:var(--skin-surface-hover)]"
  },
  textDensity: {
    id: `${typography.meta} font-semibold text-primary`,
    cardFileName: typography.cardTitle,
    tableFileName: `${typography.tableCell} font-medium text-foreground`,
    detailFileName: `${typography.body} font-semibold text-foreground`,
    label: typography.label,
    value: typography.value,
    path: typography.path,
    technical: typography.technical,
    metadata: `${typography.technical} font-mono`,
    history: typography.technical
  },
  responsive: {
    pageGrid: "grid min-w-0 gap-[var(--skin-content-gap)]",
    uploadShell: "grid gap-[var(--skin-content-gap)] lg:grid-cols-[minmax(280px,var(--skin-upload-aside-width))_minmax(0,1fr)]",
    uploadContent:
      "mx-auto w-full max-w-[var(--skin-upload-content-max-width)] min-w-0 space-y-4",
    uploadTaskGrid:
      "grid gap-[var(--skin-content-gap)] xl:grid-cols-[minmax(0,1fr)_minmax(280px,var(--skin-upload-aside-width))]",
    uploadPrimaryAction:
      "min-h-[var(--skin-touch-target-min-height)] w-full",
    libraryShell:
      "-mt-2 grid min-h-[calc(100vh-118px)] gap-3 bg-[color:var(--skin-page-bg)]",
    libraryShellExpanded:
      "lg:grid-cols-[var(--skin-library-sidebar-width)_minmax(0,1fr)]",
    libraryShellCollapsed:
      "lg:grid-cols-[var(--skin-library-sidebar-collapsed-width)_minmax(0,1fr)]",
    mobileActionBar:
      `fixed inset-x-3 bottom-3 z-40 flex min-h-[var(--skin-mobile-bottom-bar-height)] flex-wrap items-center gap-2 rounded-[var(--skin-radius-panel)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] px-3 py-3 pb-[calc(env(safe-area-inset-bottom)+0.75rem)] shadow-[var(--skin-shadow-sticky-action)] lg:inset-x-auto lg:left-1/2 lg:-translate-x-1/2 lg:px-4 lg:pb-3 ${typography.body}`,
    libraryContent:
      "mx-auto w-full max-w-[var(--skin-library-content-max-width)] min-w-0 space-y-3",
    libraryToolbar:
      "min-h-[var(--skin-toolbar-min-height)] space-y-3",
    libraryGrid:
      "grid grid-cols-2 gap-2 sm:gap-3 xl:gap-4"
  },
  media: {
    thumbnail:
      "overflow-hidden rounded-[var(--skin-radius-sm)] bg-[color:var(--skin-media-thumbnail-bg)]",
    placeholder:
      "flex h-full w-full flex-col items-center justify-center gap-1 rounded-[inherit] border border-dashed border-[color:var(--skin-media-placeholder-border)] bg-[color:var(--skin-media-placeholder-bg)] text-center text-xs text-muted-foreground",
    placeholderSm: "min-h-[var(--skin-media-placeholder-height-sm)] px-2 py-2",
    placeholderMd: "min-h-[var(--skin-media-placeholder-height-md)] px-3 py-3",
    placeholderLg: "min-h-[var(--skin-media-placeholder-height-lg)] px-4 py-5"
  },
  emptyState:
    `flex min-h-[var(--skin-empty-state-min-height)] flex-col items-center justify-center rounded-[var(--skin-radius-panel)] border border-dashed border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] p-8 text-center text-muted-foreground sm:p-10 ${typography.body}`,
  emptyStateCompact:
    `flex min-h-32 flex-col items-center justify-center rounded-[var(--skin-radius-panel)] border border-dashed border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] p-5 text-center text-muted-foreground ${typography.body}`,
  metric: {
    base: "rounded-[var(--skin-radius-card)] border border-[color:var(--skin-border)] bg-[color:var(--skin-panel-bg)] p-3 shadow-[var(--skin-shadow-card)]",
    icon: "flex h-8 w-8 shrink-0 items-center justify-center rounded-[var(--skin-radius-control)]",
    label: `truncate font-medium ${typography.label}`,
    value: "text-xl font-semibold leading-none text-foreground",
    description: typography.meta
  },
  status: {
    success: statusClass("success"),
    warning: statusClass("warning"),
    danger: statusClass("danger"),
    info: statusClass("info"),
    neutral: statusClass("neutral"),
    processing: statusClass("processing"),
    review: statusClass("review")
  },
  mobileSafeBottom: "pb-[calc(env(safe-area-inset-bottom)+0.75rem)]"
} as const;

export type SkinStatusTone = keyof typeof skin.status;
